# Generated by Django 4.0.2 on 2022-03-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_remove_user_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profile/profile_pic.jpg', null=True, upload_to='images/profile/'),
        ),
    ]
